Exception "urk" may be thrown by 'a' and automatically propagated out of 'b'. Consider adding explicit exception handling or marking with the function 'rethrowing'.
